# SPDX-License-Identifier: MIT
# Copyright David Kristiansen

repos:
  - repo: https://github.com/nshepperd/license-headers
    rev: v1.2.0
    hooks:
      - id: license-headers
        args: [--license, "MIT", --spdx, --extension=lua]
