#!/bin/bash


mkdir -p $HOME/.config
mkdir -p $HOME/.local/bin
mkdir -p $HOME/.local/share

git submodule update --init

./.local/bin/stow.sh \
  -i "^\.git" \
  -i "^"$(basename "${0}")"$"\
  -f

export ASDF_DIR="${HOME}"/.local/share/asdf
export ASDF_DATA_DIR="${HOME}"/.local/share/asdf_data
export ASDF_CONFIG_FILE="${HOME}"/.config/asdf/config

if type zsh >/dev/null; then
  direnv_shell="zsh"
else
  direnv_shell="bash"
fi


(
 cd $HOME
  asdf plugin add lazydocker https://github.com/comdotlinux/asdf-lazydocker.git
  cat .tool-versions | cut -d' ' -f1 | grep "^[^\#]" | xargs -i "${ASDF_DIR}"/bin/asdf plugin add  {}
  cat .tool-versions | cut -d' ' -f1 | grep "^[^\#]" | xargs -i "${ASDF_DIR}"/bin/asdf install {}
)

exec /bin/zsh
