# SPDX-License-Identifier: MIT
# vim-tpipeline: embeds the nvim statusline into the tmux status bar.
# (focus-events + truecolor live in general.conf.)

set -g status-left '#[bg=#32302f,fg=#a89984]  #[fg=#a89984]#S #[bg=default,fg=default]#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-left-length 99

set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
set -g status-right-length 99

set -g status-justify absolute-centre

# vim: set ft=tmux ts=2 sw=2:
