ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOCONNECT=true
ZSH_TMUX_AUTOQUIT=true
ZSH_TMUX_CONFIG="${XDG_CONFIG_HOME}/tmux/tmux.conf"
ZSH_TMUX_DEFAULT_SESSION_NAME=λ
ZSH_TMUX_AUTONAME_SESSION=true
ZSH_TMUX_UNICODE=true

