TEXMFVAR=$XDG_CACHE_HOME/texlive/2026/texmf-var
TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/2026/texmf-config
TEXMFHOME=$XDG_DATA_HOME/texmf
PATH=/usr/local/texlive/2026/bin/x86_64-linux:$PATH

# vim: set ft=ini:

