# Keybindings

# Extra splits (keep default " and % intact)
bind | split-window -h
bind - split-window -v

unbind-key .
bind-key . command-prompt -p "Rename session:" "rename-session '%%'"

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Allow Ctrl-\ to pass through to applications (for SIGQUIT)
unbind-key -T root C-\\
unbind-key -T copy-mode-vi C-\\

